# You can use iterative BFS solution to solve this problem, but there is
# a way to solve this using recursive "DFS" solution. You just need to
# keep track of which level you are entering at each recursion stack...
